### ISSUE TITLE
Include honeypot to lower spam without captcha

### ISSUE THREAD

**Issue by jasonday** [typemill-resources/contactform#1]
https://www.ibm.com/docs/en/acvfc?topic=security-using-honeypot-spam-protection
https://racheleditullio.com/blog/2020/04/add-an-accessible-honeypot-field-to-your-php-form/

Due to some "buggyness" with both the captcha and recaptcha, another option is to include a honey pot in the form to catch bots that are autofilling the form and submitting.

**Comment by jasonday** [comment]
I stand corrected. It looks like you're already using it. Is there a log output of the failures?

**Comment by trendschau** [comment]
Yes, you can activate a log in the developer settings of the system. Logfile is stored in the cache if I remember correctly.
